In [1]:
import numpy as np
import re
import json
import pandas as pd

In [26]:
model = "gpt-3.5-turbo"

labels = pd.read_csv("results.txt", delimiter = ",").loc[:,["pairid", " varA","varB","dataset","groundtruth"]]
labels['pairid'] = labels['pairid'].str.extract('(\d{4})').astype(int) # convert pairid to int
labels["groundtruth"] = labels["groundtruth"].str.replace(r'\s+', '', regex=True) # remove white space in labels

weights = pd.read_csv("pairmeta.txt", delimiter = " ", header = None).iloc[:,[0,5]]
weights.rename(columns = {0:"pairid", 5:"weight"}, inplace=True)
weights['pairid'] = weights['pairid'].astype(int) # convert pairid to int

merged_df = labels.merge(weights, on='pairid')

with open(model + "_response_nosys.json", "r") as file:
    loaded_data = json.load(file)
    
merged_df.head()

   pairid       varA            varB  dataset groundtruth  weight
0       1   Altitude     Temperature      DWD          ->   0.166
1       2   Altitude   Precipitation      DWD          ->   0.166
2       3  Longitude     Temperature      DWD          ->   0.167
3       4   Altitude  Sunshine hours      DWD          ->   0.166
4       5        Age          Length  Abalone          ->   0.143

In [36]:
def add_prediction(merged_df, loaded_data, model):
    merged_df = merged_df.set_index('pairid')
    for response in loaded_data:
        pairid, resid, answer = extract_answers(response)
        print(pairid,resid)
        col = "AtoB" if resid == "1" else "BtoA"
        merged_df.loc[int(pairid),col] = "Yes" if answer == "Yes." else "No" if answer == "No." else answer
        print("Converted:", merged_df.loc[int(pairid),col])
    return merged_df


def extract_answers(s):
    # Compile regex patterns
    
    pairid_pattern = re.compile(r"\{'pair0(\d{3}),_res(\d)")
    
    # Search for pairid
    pairid_match = pairid_pattern.search(str(s))
    pairid = pairid_match.group(1) if pairid_match else None
    resid = pairid_match.group(2) if pairid_match else None
    
    # Search for answer
    ans = s["pair0"+ str(pairid) + ',_res' + str(resid)]["choices"][0]["message"]['content']
    
    return pairid, resid, ans

In [37]:
loaded_data[1]

{'pair0001,_res2': {'id': 'chatcmpl-7z6lm8UI9dfx5AzCeFfm8FOJb77Mg',
  'object': 'chat.completion',
  'created': 1694798386,
  'model': 'gpt-3.5-turbo-0613',
  'choices': [{'index': 0,
    'message': {'role': 'assistant', 'content': 'No.'},
    'finish_reason': 'stop'}],
  'usage': {'prompt_tokens': 27, 'completion_tokens': 2, 'total_tokens': 29}}}

In [38]:
results = add_prediction(merged_df, loaded_data, model)

001 1
Converted: Yes
001 2
Converted: No
002 1
Converted: Yes
002 2
Converted: No
003 1
Converted: No
003 2
Converted: No
004 1
Converted: No
004 2
Converted: No
005 1
Converted: No
005 2
Converted: No
006 1
Converted: Yes
006 2
Converted: No
007 1
Converted: No
007 2
Converted: No
008 1
Converted: No
008 2
Converted: No
009 1
Converted: No
009 2
Converted: No
010 1
Converted: No
010 2
Converted: No
011 1
Converted: Yes
011 2
Converted: No
012 1
Converted: No
012 2
Converted: No
013 1
Converted: Yes
013 2
Converted: No
014 1
Converted: Yes
014 2
Converted: No
015 1
Converted: Yes
015 2
Converted: No
016 1
Converted: Yes
016 2
Converted: No
017 1
Converted: No
017 2
Converted: No
018 1
Converted: No
018 2
Converted: No
019 1
Converted: No
019 2
Converted: No
020 1
Converted: Yes
020 2
Converted: No
021 1
Converted: No
021 2
Converted: No
022 1
Converted: No
022 2
Converted: No
023 1
Converted: No
023 2
Converted: No
024 1
Converted: Yes
024 2
Converted: No
025 1
Converted: Yes
025 2
Converted: No
026 1
Converted: Yes
026 2
Converted: No
027 1
Converted: Yes
027 2
Converted: No
028 1
Converted: Yes
028 2
Converted: No
029 1
Converted: Yes
029 2
Converted: No
030 1
Converted: Yes
030 2
Converted: No
031 1
Converted: Yes
031 2
Converted: No
032 1
Converted: No
032 2
Converted: No
033 1
Converted: Yes
033 2
Converted: No
034 1
Converted: No
034 2
Converted: No
035 1
Converted: Yes
035 2
Converted: No
036 1
Converted: Yes
036 2
Converted: No
037 1
Converted: Yes
037 2
Converted: No
038 1
Converted: No
038 2
Converted: No
039 1
Converted: No
039 2
Converted: No
040 1
Converted: Yes
040 2
Converted: No
041 1
Converted: No
041 2
Converted: No
042 1
Converted: No
042 2
Converted: No
043 1
Converted: Yes
043 2
Converted: No
044 1
Converted: Yes
044 2
Converted: No
045 1
Converted: Yes
045 2
Converted: No
046 1
Converted: Yes
046 2
Converted: No
047 1
Converted: No
047 2
Converted: No
048 1
Converted: No
048 2
Converted: Yes
049 1
Converted: Yes
049 2
Converted: Yes
050 1
Converted: No
050 2
Converted: Yes
051 1
Converted: Yes
051 2
Converted: Yes
052 1
Converted: No
052 2
Converted: No
053 1
Converted: Yes
053 2
Converted: Yes
054 1
Converted: Yes
054 2
Converted: No
055 1
Converted: Yes
055 2
Converted: Yes
056 1
Converted: No
056 2
Converted: No
057 1
Converted: No
057 2
Converted: No
058 1
Converted: No
058 2
Converted: No
059 1
Converted: No
059 2
Converted: No
060 1
Converted: No
060 2
Converted: No
061 1
Converted: No
061 2
Converted: No
062 1
Converted: No
062 2
Converted: No
063 1
Converted: No
063 2
Converted: No
064 1
Converted: Yes
064 2
Converted: No
065 1
Converted: No
065 2
Converted: No
066 1
Converted: Yes
066 2
Converted: Yes
067 1
Converted: No
067 2
Converted: No
068 1
Converted: No
068 2
Converted: No
069 1
Converted: No
069 2
Converted: Yes
070 1
Converted: Yes
070 2
Converted: No
071 1
Converted: No
071 2
Converted: No
072 1
Converted: Yes
072 2
Converted: No
073 1
Converted: Yes
073 2
Converted: Yes
074 1
Converted: Yes
074 2
Converted: Yes
075 1
Converted: No
075 2
Converted: Yes
076 1
Converted: Yes
076 2
Converted: No
077 1
Converted: No
077 2
Converted: Yes
078 1
Converted: Yes
078 2
Converted: No
079 1
Converted: No
079 2
Converted: Yes
080 1
Converted: No
080 2
Converted: Yes
081 1
Converted: Yes
081 2
Converted: No
082 1
Converted: Yes
082 2
Converted: Yes
083 1
Converted: Yes
083 2
Converted: Yes
084 1
Converted: No
084 2
Converted: Yes
085 1
Converted: No
085 2
Converted: No
086 1
Converted: Yes
086 2
Converted: No
087 1
Converted: No
087 2
Converted: No
088 1
Converted: No
088 2
Converted: No
089 1
Converted: No
089 2
Converted: No
090 1
Converted: No
090 2
Converted: No
091 1
Converted: Yes
091 2
Converted: No
092 1
Converted: No
092 2
Converted: Yes
093 1
Converted: Yes
093 2
Converted: No
094 1
Converted: No
094 2
Converted: No
095 1
Converted: Yes
095 2
Converted: No
096 1
Converted: Yes
096 2
Converted: No
097 1
Converted: Yes
097 2
Converted: No
098 1
Converted: Yes
098 2
Converted: No
099 1
Converted: No
099 2
Converted: Yes
100 1
Converted: Yes
100 2
Converted: No
101 1
Converted: Yes
101 2
Converted: Yes
102 1
Converted: No
102 2
Converted: No
103 1
Converted: No
103 2
Converted: No
104 1
Converted: No
104 2
Converted: No
105 1
Converted: No
105 2
Converted: No
106 1
Converted: No
106 2
Converted: No
107 1
Converted: Yes
107 2
Converted: No
108 1
Converted: No
108 2
Converted: No

In [40]:
results["AtoB"].unique()

array(['Yes', 'No'], dtype=object)

In [41]:
results["gt_AtoB"] = np.where(results["groundtruth"] == "->", "Yes", "No")
results["gt_BtoA"] = np.where(results["groundtruth"] == "->", "No", "Yes")
results["correct_AtoB"] = np.where(results["gt_AtoB"] == results["AtoB"], 1, 0)
results["correct_BtoA"] = np.where(results["gt_BtoA"] == results["BtoA"], 1, 0)
wtd_acc = (sum(results["correct_AtoB"]*results["weight"]) + sum(results["correct_BtoA"]*results["weight"])) / (results["weight"].sum()*2)
acc = (sum(results["correct_AtoB"]) + sum(results["correct_BtoA"])) / 108 / 2
print("acc:", acc, "weighted acc:", wtd_acc)

acc: 0.7407407407407407 weighted acc: 0.7556919731575289

In [42]:
results

,varA,varB,dataset,groundtruth,weight,AtoB,BtoA,gt_AtoB,gt_BtoA,correct_AtoB,correct_BtoA
pairid,,,,,,,,,,,
1,Altitude,Temperature,DWD,->,0.166,Yes,No,Yes,No,1,1
2,Altitude,Precipitation,DWD,->,0.166,Yes,No,Yes,No,1,1
3,Longitude,Temperature,DWD,->,0.167,No,No,Yes,No,0,1
4,Altitude,Sunshine hours,DWD,->,0.166,No,No,Yes,No,0,1
5,Age,Length,Abalone,->,0.143,No,No,Yes,No,0,1
...,...,...,...,...,...,...,...,...,...,...,...
104,time for passing 1. segment,time for passing 2. segment,D. Janzing,->,0.200,No,No,Yes,No,0,1
105,pixel vector of a patch,total brightness at the screen,D. Janzing,->,0.500,No,No,Yes,No,0,1
106,time required for one round,voltage,D. Janzing,<-,1.000,No,No,No,Yes,1,0
107,strength of contrast,answer correct or not,"Schuett, edited by D. Janzing",->,1.000,Yes,No,Yes,No,1,1
108,time for 1/6 rotation,temperature,D. Janzing,<-,1.000,No,No,No,Yes,1,0